modLoader="javafml" #mandatory
loaderVersion="[47,)" #mandatory
license="All rights reserved"
[[mods]] #mandatory
modId="tetrajs" #mandatory
version="1.0" #mandatory
displayName="TetraJS" #mandatory
authors="Neha YoruNina" #optional
description='''TetraJS'''
[[dependencies.tetrajs]] #optional
modId="forge" #mandatory
mandatory=true #mandatory
versionRange="[47,)" #mandatory
ordering="NONE"
side="BOTH"
[[dependencies.tetrajs]]
modId="minecraft"
mandatory=true
versionRange="[1.20, 1.21)"
ordering="NONE"
side="BOTH"
